import type { Part } from '@/lib/types'

/**
 * Parts & accessories — the margin + attach-rate layer. This catalog is
 * deliberately built around the KNOWN Sur-Ron owner pain points surfaced in
 * research (locked stock controller, weak forks, undersized brakes, melting
 * battery connectors, disliked tyres) so every SKU has a real "why". Fitment
 * ids map to models — the attach-rate engine on the PDP and parts PLP.
 * Prices [VERIFY] against supplier cost + target margin.
 */
export const parts: Part[] = [
  {
    id: 'p-rims',
    handle: 'performance-falgar-offroad-dack',
    name: { sv: 'Performance-fälgar + off-road-däck', en: 'Performance rims + off-road tyres' },
    category: 'wheels-tires',
    price: { sek: 4990, eur: 445 },
    images: [{ src: '/parts/rims-offroad.svg', alt: { sv: 'Performance-fälgar', en: 'Performance rims' }, width: 1000, height: 1000 }],
    summary: { sv: 'Lättare fälgar och rejäla terrängdäck som ersätter det mjuka originalgummit.', en: 'Lighter rims and serious off-road tyres that replace the soft stock rubber.' },
    description: [
      { sv: 'Originaldäcken är en vanlig svaghet. Det här setet ger fäste i lös terräng och tål hårdare körning.', en: 'The stock tyres are a common weak point. This set adds grip in loose terrain and takes harder riding.' },
    ],
    fitment: ['light-bee-x', 'ultra-bee', 'storm-bee'],
    availability: { state: 'in_stock', stockQty: 12 },
    sku: 'ELDR-RIM-01',
    upgradeReason: { sv: 'Originaldäcken får ofta kritik för svagt fäste.', en: 'Stock tyres are frequently criticised for weak grip.' },
    verify: true,
  },
  {
    id: 'p-throttle',
    handle: 'mjuk-elektronisk-gasspjall',
    name: { sv: 'Mjukare elektronisk gasrespons', en: 'Smoother electronic throttle' },
    category: 'controls',
    price: { sek: 690, eur: 62 },
    images: [{ src: '/parts/throttle.svg', alt: { sv: 'Elektroniskt gasspjäll', en: 'Electronic throttle' }, width: 1000, height: 1000 }],
    summary: { sv: 'Eftermarknadsgasspjäll med mjukare respons — bättre kontroll i teknisk terräng.', en: 'Aftermarket throttle with a smoother response — better control in technical terrain.' },
    description: [{ sv: 'Dämpar det hackiga on/off-beteendet i originalgasen för mer precis lågfartskontroll.', en: 'Tames the abrupt on/off feel of the stock throttle for more precise low-speed control.' }],
    fitment: ['light-bee-x', 'ultra-bee'],
    availability: { state: 'in_stock', stockQty: 20 },
    sku: 'ELDR-THR-01',
    upgradeReason: { sv: 'Originalgasen upplevs ofta som hackig.', en: 'The stock throttle is often felt to be abrupt.' },
  },
  {
    id: 'p-kke-forks',
    handle: 'kke-framgafflar',
    name: { sv: 'KKE uppgraderade framgafflar', en: 'KKE upgraded front forks' },
    category: 'suspension',
    brand: 'KKE',
    price: { sek: 6490, eur: 579 },
    images: [{ src: '/parts/kke-forks.svg', alt: { sv: 'KKE framgafflar', en: 'KKE front forks' }, width: 1000, height: 1000 }],
    summary: { sv: 'Styvare, mer justerbara framgafflar som ersätter de mjuka originalen.', en: 'Stiffer, more adjustable front forks that replace the soft stock units.' },
    description: [{ sv: 'Originalgafflarna (KKE/DNM) bottnar lätt vid hårdare körning. KKE-uppgraderingen ger bättre dämpning och kontroll.', en: 'The stock forks (KKE/DNM) bottom out easily under harder riding. The KKE upgrade adds damping and control.' }],
    fitment: ['light-bee-x'],
    availability: { state: 'build_to_order', leadTimeDays: [10, 21] },
    sku: 'ELDR-FRK-KKE',
    upgradeReason: { sv: 'Svaga originalgafflar är en av de vanligaste klagomålen.', en: 'Weak stock forks are one of the most common complaints.' },
  },
  {
    id: 'p-bar-risers',
    handle: 'styrfaste-riser',
    name: { sv: 'Styrfäste / riser (barmonterat)', en: 'Handlebar clamp / riser mount' },
    category: 'ergonomics',
    price: { sek: 890, eur: 79 },
    images: [{ src: '/parts/bar-risers.svg', alt: { sv: 'Styrfäste riser', en: 'Bar riser' }, width: 1000, height: 1000 }],
    summary: { sv: 'CNC-frästa styrfästen som höjer styret och sitter barmonterat för att inte vrida sig vid islag.', en: 'CNC bar clamps that raise the bars and mount to the bar so they will not twist on impact.' },
    description: [{ sv: 'Barmonterad design gör att styret sitter kvar vid ett fall — inget vridande som med enklare klämmor.', en: 'Bar-mounted design keeps the bars put in a crash — no twisting like simpler clamps.' }],
    fitment: ['light-bee-x', 'ultra-bee', 'storm-bee'],
    availability: { state: 'in_stock', stockQty: 30 },
    sku: 'ELDR-BAR-01',
  },
  {
    id: 'p-footpegs',
    handle: 'cnc-fotpinnar',
    name: { sv: 'CNC-frästa fotpinnar', en: 'CNC-milled footpegs' },
    category: 'ergonomics',
    price: { sek: 1290, eur: 115 },
    images: [{ src: '/parts/footpegs.svg', alt: { sv: 'CNC fotpinnar', en: 'CNC footpegs' }, width: 1000, height: 1000 }],
    summary: { sv: 'Breda, vassa fotpinnar i CNC-fräst aluminium för bättre grepp stående.', en: 'Wide, aggressive CNC-milled aluminium footpegs for better grip standing up.' },
    description: [{ sv: 'Större plattform och vassare pigg ger säkrare fotfäste i terräng än originalpinnarna.', en: 'A larger platform and sharper teeth give more secure footing off-road than the stock pegs.' }],
    fitment: ['light-bee-x', 'ultra-bee', 'storm-bee'],
    availability: { state: 'in_stock', stockQty: 24 },
    sku: 'ELDR-PEG-01',
  },
  {
    id: 'p-brake-kit',
    handle: '250mm-bromsskiva-kit',
    name: { sv: '250 mm oversize bromsskive-kit', en: '250 mm oversized brake disc kit' },
    category: 'brakes',
    price: { sek: 2490, eur: 222 },
    images: [{ src: '/parts/brake-kit.svg', alt: { sv: '250 mm bromsskive-kit', en: '250 mm brake disc kit' }, width: 1000, height: 1000 }],
    summary: { sv: 'Större 250 mm bromsskiva med adapter — kraftigare, mer uthållig inbromsning.', en: 'A larger 250 mm brake disc with adapter — stronger, more fade-resistant braking.' },
    description: [{ sv: 'Originalbromsarna är MTB-dimensionerade (~203 mm). Uppgradering till 250 mm ger mer bromskraft för tyngre/snabbare körning.', en: 'The stock brakes are MTB-sized (~203 mm). Upgrading to 250 mm adds stopping power for heavier/faster riding.' }],
    fitment: ['light-bee-x', 'ultra-bee'],
    availability: { state: 'in_stock', stockQty: 10 },
    sku: 'ELDR-BRK-250',
    upgradeReason: { sv: 'Underdimensionerade originalbromsar är ett känt problem.', en: 'Undersized stock brakes are a known issue.' },
  },
  {
    id: 'p-controller',
    handle: 'sport-styrenhet',
    name: { sv: 'Sport-styrenhet (uppgraderad controller)', en: 'Sport controller (upgraded)' },
    category: 'drivetrain',
    price: { sek: 3990, eur: 356 },
    images: [{ src: '/parts/controller.svg', alt: { sv: 'Sport-styrenhet', en: 'Sport controller' }, width: 1000, height: 1000 }],
    summary: { sv: 'Uppgraderad styrenhet som frigör mer ström och effekt (endast för off-road-bruk).', en: 'Upgraded controller that unlocks more current and power (off-road use only).' },
    description: [{ sv: 'Originalcontrollern är strömbegränsad. Sportcontrollern ger mer effekt — endast för privat mark/bana, påverkar homologering och garanti.', en: 'The stock controller is current-limited. The sport controller adds power — private land/track only; it affects homologation and warranty.' }],
    fitment: ['light-bee-x'],
    availability: { state: 'in_stock', stockQty: 8 },
    sku: 'ELDR-CTRL-01',
    upgradeReason: { sv: 'Den låsta originalcontrollern är den vanligaste effektuppgraderingen.', en: 'The locked stock controller is the most common power upgrade.' },
  },
  {
    id: 'p-connector',
    handle: 'forseglad-batterikontakt',
    name: { sv: 'Förseglad batterikontakt', en: 'Sealed battery connector' },
    category: 'protection',
    price: { sek: 349, eur: 31 },
    images: [{ src: '/parts/connector.svg', alt: { sv: 'Batterikontakt', en: 'Battery connector' }, width: 1000, height: 1000 }],
    summary: { sv: 'Kraftigare, förseglad huvudkontakt som motverkar överhettning och smälta original.', en: 'A heavier, sealed main connector that resists the overheating and melting of stock ones.' },
    description: [{ sv: 'Smälta batterikontakter är ett vanligt fel. Uppgraderingen tål högre ström och håller vatten ute.', en: 'Melted battery connectors are a common failure. This upgrade handles higher current and keeps water out.' }],
    fitment: ['light-bee-x', 'ultra-bee', 'storm-bee'],
    availability: { state: 'in_stock', stockQty: 40 },
    sku: 'ELDR-CON-01',
    upgradeReason: { sv: 'Smälta originalkontakter rapporteras ofta av ägare.', en: 'Melted stock connectors are frequently reported by owners.' },
  },
]
